services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    depends_on:
      - postgres
    container_name: api
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=788556
      - POSTGRES_DB=high_load
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres

volumes:
  postgres-data:
networks:
  draw-rec-backend-network:
    driver: bridge
